pipeline:
  name: pipelinenondefaultbranch
  identifier: pipelinenondefaultbranch
  projectIdentifier: testproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "some random test"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
