pipeline:
  name: remotetriggertestpipeline
  identifier: remotetriggertestpipeline
  projectIdentifier: testproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "test"

                          echo <+eventPayload>

                          cat>>myfile.json<<EOF
                          <+eventPayload>
                          EOF

                          cat myfile.json 

                          echo "final test"
                          microdnf install jq 

                          myvar=$(echo '<+eventPayload>')

                          echo "$myvar" | jq .
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "test2"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: somevar
      type: String
      description: ""
      required: false
      value: <+input>
