pipeline:
  name: testhelmk8
  identifier: testhelmk8
  projectIdentifier: testproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: somerandomtest
        identifier: somerandomtest
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+pipeline.variables.testenv>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: qq
        identifier: qq
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: helmk8
          environment:
            environmentRef: devenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testinfra
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          export KUBECONFIG=${HARNESS_KUBE_CONFIG_PATH}

                          cp ${HARNESS_KUBE_CONFIG_PATH} /opt/harness-delegate/mydelegateconfig.txt

                          kubectl config view --raw
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    delegateSelectors:
                      - kubernetes-delegate
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - csamitk8delegate
  allowStageExecutions: true
  variables:
    - name: myrelease
      type: String
      description: ""
      required: false
      value: <+input>
