pipeline:
  name: testnew
  identifier: testnew
  projectIdentifier: ajhacse
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ah
        identifier: ah
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "this is test"
                          echo "<+secrets.getValue('account.testsecret')>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
