pipeline:
  name: testcdtpipeline
  identifier: testcdtpipeline
  projectIdentifier: testproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testcdtstage
        identifier: testcdtstage
        description: ""
        type: Deployment
        spec:
          deploymentType: CustomDeployment
          execution:
            steps:
              - step:
                  type: FetchInstanceScript
                  name: FetchInstanceScript_1
                  identifier: FetchInstanceScript_1
                  spec: {}
                  timeout: 10m
            rollbackSteps: []
          customDeploymentRef:
            templateRef: org.cdttest
            versionLabel: "1.2"
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
