pipeline:
  name: testpipelinereproankit
  identifier: testpipelinereproankit
  projectIdentifier: cseajhang
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdfsdf
        identifier: sdfsdf
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: dasdadsdasd
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
