pipeline:
  name: tetabhishekpipeline
  identifier: tetabhishekpipeline
  projectIdentifier: cseajhang
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: somestage
        identifier: somestage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "this is testbranch2"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
