pipeline:
  name: artifactpipeline
  identifier: artifactpipeline
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: artifactstage
        identifier: artifactstage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: artifactservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dummy
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |+
                          echo "test"

                          echo <+stage.spec.serviceConfig.serviceDefinition.spec.artifacts.primary>

                          echo "======"

                          echo <+pipeline.stages.artifactstage.service.artifactservice.spec.artifacts.primary.tempartifact.imagePath>

                          echo "****"

                          echo <+artifacts.primary.identifier.tempartifact.imagePath>

                          echo "======"
                          echo <+pipeline.stages.artifactstage.service.artifactservice.spec.artifacts.primary.secartifact.imagePath>


                          echo "======"


                          echo "======"

                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: myvar
            type: String
            description: ""
            value: adsaddsd
    - stage:
        name: scriptstage
        identifier: scriptstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "testmultistage"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
