pipeline:
  name: artifactpipeline
  identifier: artifactpipeline
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: scriptstage
        identifier: scriptstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.variables.test>

                          echo <+"arn:aws:iam::" + <+pipeline.variables.test> + ":role/datalake-" + <+pipeline.variables.test> + "-logstash-eso-role">
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  when:
                    stageStatus: Success
                  failureStrategies: []
              - step:
                  type: ShellScript
                  name: step2
                  identifier: step2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "testmulti stage"

                          echo <+serviceVariables>

                          echo <+pipeline.delegateSelectors[0].delegateSelectors>
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - groupdelegate
                  timeout: 10m
                  failureStrategies: []
        tags: {}
    - stage:
        name: artifactstage
        identifier: artifactstage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: artifactservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            environmentInputs:
              identifier: dev
              type: PreProduction
              variables:
                - name: connectorenv
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: qa
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: "str=`echo $myvar3 | sed 's/{//g' | sed 's/}//g'`\ndelimiter=\", \"\ns=$str$delimiter\narray=();\n\nwhile [[ $s ]]; do\n\tarray+=( \"${s%%\"$delimiter\"*}\" );\n\ts=${s#*\"$delimiter\"};\ndone;\ndeclare -p array\n\nfor i in \"${array[@]}\"\ndo\n   echo $i\ndone\n\n"
                    environmentVariables:
                      - name: myvar3
                        type: String
                        value: <+serviceVariables>
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10s
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: myvar
            type: String
            description: ""
            value: adsaddsd
        when:
          pipelineStatus: All
  variables:
    - name: convar
      type: String
      description: ""
      value: qa
    - name: dummy1
      type: String
      description: ""
      value: dummy2
    - name: dummy2
      type: String
      description: ""
      value: manifest
    - name: con2
      type: String
      description: ""
      value: <+input>
    - name: con1
      type: String
      description: ""
      value: <+input>
    - name: con3
      type: String
      description: ""
      value: <+input>
  delegateSelectors:
    - groupdelegate
  allowStageExecutions: true
