pipeline:
  name: artifactpipeline
  identifier: artifactpipeline
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: scriptstage
        identifier: scriptstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "testmultistage"
                          echo <+steps.get_current_replicas.output.outputVariables.PodCount>*<+serviceVariables.CanaryPercentage.split(',')[4]>/100
                          echo <+somevaribale.which.does.not.exist>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.dummy> == "True"
                  failureStrategies: []
              - step:
                  type: ShellScript
                  name: step2
                  identifier: step2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "testmulti stage"

                          echo <+serviceVariables>

                          echo <+pipeline.delegateSelectors[0].delegateSelectors>
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - groupdelegate
                  timeout: 10m
                  failureStrategies: []
        tags: {}
    - stage:
        name: artifactstage
        identifier: artifactstage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: artifactservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: qa
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |+
                          echo "test"


                          export myvar4=`echo "def,geh,ijkl"`
                          echo $myvar4
                          echo <+$myvar4.split(',')[1]>

                          echo <+"echo <+serviceVariables>".split(,)>

                          echo $myvar2


                    environmentVariables:
                      - name: myvar
                        type: String
                        value: <+serviceVariables>
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10s
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: myvar
            type: String
            description: ""
            value: adsaddsd
        when:
          pipelineStatus: All
  variables:
    - name: convar
      type: String
      description: ""
      value: qa
    - name: dummy
      type: String
      description: ""
      value: <+input>
  delegateSelectors:
    - groupdelegate
