pipeline:
  name: dadasd
  identifier: dadasd
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dsdadsad
        identifier: dsdadsad
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+secrets.getValue("account.hashicorpvault://usheervaultest/newusheer/harness_vault_validation#value")> > /tmp/testsecretvalue.txt


                          echo <+secrets.getValue("account.hashicorpvault://usheervaultest/csetestssh#value")> > /tmp/testsecretvaluen.txt


                          echo <+secrets.getValue("account.csesshreproref")>
                    environmentVariables: []
                    outputVariables: []
                    executionTarget:
                      connectorRef: account.ajhareprossh
                      host: ec2-3-83-15-117.compute-1.amazonaws.com
        tags: {}
  delegateSelectors:
    - docker-delegate
