pipeline:
  name: dadasd
  identifier: dadasd
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dsdadsad
        identifier: dsdadsad
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo <+secrets.getValue("account.hashicorpvault://usheervaultest/csessh#csesshref")> >> temp.txt
                    environmentVariables: []
                    outputVariables: []
        tags: {}
  delegateSelectors:
    - docker-delegate
