pipeline:
  name: dadasd
  identifier: dadasd
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dsdadsad
        identifier: dsdadsad
        description: dasdasddaasddsad
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+secrets.getValue("account.bitbucket_tokenusheer")> >> abc.txt

                          cat abc.txt
                    environmentVariables:
                      - name: var1
                        type: String
                        value: <+pipeline.variables.test1>
                      - name: var2
                        type: String
                        value: <+pipeline.variables.test2>
                    outputVariables: []
                    executionTarget:
                      connectorRef: account.ajhareprossh
                      host: ec2-3-83-15-117.compute-1.amazonaws.com
        tags: {}
        delegateSelectors:
          - ajha-ng-delegate
  delegateSelectors:
    - docker-delegate
  variables:
    - name: test1
      type: String
      description: ""
      value: this is
    - name: test2
      type: String
      description: ""
      value: being displayed
    - name: dadasda
      type: String
      description: ""
      value: dadsad
