pipeline:
  name: dsadash
  identifier: dsadas
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dsadsad
        identifier: dsadsad
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "abcd"
                          pwd
                          sleep 600
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - ajha-ng-delegate
                  timeout: 10m
                  failureStrategies: []
        tags: {}
