pipeline:
  name: dsadash
  identifier: dsadas
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dsadsad
        identifier: dsadsad
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #echo "run curl"
                          #curl -vvv http://requestb.in/
                          #echo "curl ended"
                          echo $username

                          echo "testing log output"

                          curl -o harness-delegate.tar.gz "https://app.harness.io/api/setup/delegates/download?accountId=jDOmhrFmSOGZJ1C91UC_hg&token=eyJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6ImRlbGVnYXRlLmpET21ockZtU09HWkoxQzkxVUNfaGciLCJpc3MiOiJIYXJuZXNzIEluYyIsImV4cCI6MTY4MzcwMjU2OSwiaWF0IjoxNjgzNjk4OTY5fQ.D1-vimCo-pUEGKBGBwzmqHNdZo3RojHnvS6RgcvW04o&delegateName=qa&delegateProfileId=LF_VV5urRlWojpiBwYgU9Q&tokenName=default"

                          echo "testing it again"

                          echo "script output is jumbled"
                    environmentVariables:
                      - name: username
                        type: String
                        value: testuser
                    outputVariables: []
                    delegateSelectors:
                      - ajha-ng-delegate
                  timeout: 10m
                  failureStrategies: []
        tags: {}
