pipeline:
  name: dsdada
  identifier: dsdada
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: dadasasd
        identifier: dadasasd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "dadasd"
                    environmentVariables: []
                    outputVariables: []
        tags: {}
