pipeline:
  name: jiraapprovaltest
  identifier: jiraapprovaltest
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: jiraapproval
        identifier: jiraapproval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsadad
                  identifier: dsadad
                  type: JiraApproval
                  timeout: 1d
                  spec:
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions:
                          - key: Status
                            operator: equals
                            value: To Do
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions: []
                    connectorRef: account.NandeeshJira
                    projectKey: TJI
                    issueType: Bug
                    issueKey: CSE-114
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "success"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
