pipeline:
  name: matrix-pipeline
  identifier: matrixpipeline
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: echoMatrixSettings
        identifier: echoMatrixSettings
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: echo
                  identifier: echo
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "iteration index = <+strategy.iteration>"  
                          echo "total iterations = <+strategy.iterations>"  
                          echo "stage values (parent):"  
                          echo "Current version for stage: <+stage.matrix.service>"  
                          echo "Current environment for stage: <+stage.matrix.environment>"  
                          echo "step values (local):"  
                          echo "Current item (version): <+repeat.item>"  
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  failureStrategies: []
                  strategy:
                    repeat:
                      items:
                        - "18"
                        - "17"
                        - "16"
                        - "15"
                        - "14"
                        - "13"
                        - "12"
                        - "11"
                        - "10"
                        - "9"
                    maxConcurrency: 2
        tags: {}
        strategy:
          matrix:
            service:
              - svc1
              - thissvc
              - svc3
            environment:
              - env1
              - env2
            exclude:
              - service: svc1
                environment: env1
          maxConcurrency: 2
        variables:
          - name: testsvc
            type: String
            description: ""
            value: yourservice-myservice
          - name: testsplit
            type: String
            description: ""
            value: <+<+stage.variables.testsvc>.split('-')[0]>
