pipeline:
  name: mytestpolicypipeline
  identifier: mytestpolicypipeline
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage1
        identifier: teststage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TerraformPlan_1
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: jkjl
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: testgithubaccount
                            repoName: mklm
                            gitFetchType: Branch
                            branch: mkmk
                            folderPath: mcvcb
                          type: Github
                      secretManagerRef: harnessSecretManager
                  timeout: 10m
        tags: {}
    - stage:
        name: sasa
        identifier: sasa
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8service
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      type: DockerRegistry
                      spec:
                        tag: <+input>.allowedValues(abcd)
          environment:
            environmentRef: dev
            environmentInputs:
              identifier: dev
              type: PreProduction
              variables:
                - name: connectorenv
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: qa
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
