pipeline:
  name: temp
  identifier: temp
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dummy
                  identifier: dummy
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "printing vars"
                          echo "<+stage.variables>"
                          vararray=($(echo <+stage.variables> | sed 's/^.//' | sed 's/.$//' | awk -F ', ' '{ for (i = 0; ++i <= NF;) print $i }' )

                          echo ${vararray}
                          for i in "${vararray[@]}"; do
                            var=${i//=/=\"}
                            newvar=$(echo "${var//'\n'/\"'\n'\"}\"" | awk '{$1=$1;print}')
                            echo "export TF_VAR_${newvar}"
                            eval "export TF_VAR_${newvar}"
                           done
                          }
                          export_vars
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: var1
            type: String
            description: ""
            value: dssadasd
          - name: var2
            type: String
            description: ""
            value: dasdad
  variables:
    - name: testvar
      type: String
      default: "false"
      description: ""
      value: <+input>.allowedValues(true,false)
