pipeline:
  name: temp
  identifier: temp
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dummy
                  identifier: dummy
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          i=1
                          while [ $i -le 10 ]
                          do
                              echo "Line ${i}"
                              i=$(($i+1))
                          done
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
