pipeline:
  name: temp
  identifier: temp
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dummy
                  identifier: dummy
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "printing vars"
                          echo "<+stage.variables>"
                          vararray=($(echo <+stage.variables> | sed 's/^.//' | sed 's/.$//' | awk -F ', ' '{ for (i = 0; ++i <= NF;) print $i }' ))


                          for item in "${vararray[@]}"
                          do
                              echo $item | awk -F'=' '{print $1}'
                              echo $item | awk -F'=' '{print $2}'
                          done
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: var1
            type: String
            description: ""
            value: dssadasd
          - name: var2
            type: String
            description: ""
            value: dasdad
  variables:
    - name: testvar
      type: String
      default: "false"
      description: ""
      value: <+input>.allowedValues(true,false)
