pipeline:
  name: temp
  identifier: temp
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dummy
                  identifier: dummy
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |+
                          foo=$(echo "foo & bar" | tee /dev/tty0)

                          echo <+<+pipeline.variables.somevar>.replace('_','-')>
                          echo <+pipeline.variables.testvar>
                          foo=$(echo "bar")
                          cat <<_EOF_
                          $foo
                          _EOF_
                          microdnf install jq
                          echo "printing secret"
                          echo <+secret.getValue("account.sshsecretfilenew")>
                          echo "printing secret"
                          echo <+secret.getValue("account.sshsecretfilenew")> > /opt/harness-delegate/secretoutput.txt
                          echo <+secrets.getValue("account.ajhaaccountleveltest")>
                          echo "text secret is: " <+pipeline.variables.testvar>
                          echo <+<+pipeline.variables.envVar>.split('-')[0]>

                          function printInfo()
                          {

                          echo "printing info"

                          }

                          printInfo



                    environmentVariables:
                      - name: testpath
                        type: String
                        value: /tmp/def
                    outputVariables:
                      - name: ipaddress
                        type: String
                        value: ipaddress
                    delegateSelectors:
                      - ajha-ng-delegate
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: Http
                  name: HTTP_1
                  identifier: HTTP_1
                  spec:
                    url: https://httpbin.org/anything
                    method: GET
                    headers: []
                    outputVariables:
                      - name: hostname
                        value: <+json.select(".headers.<+pipeline.variables.dummy>", httpResponseBody)>
                        type: String
                  timeout: 10s
        tags: {}
        variables:
          - name: var1
            type: String
            description: ""
            value: dssadasd
          - name: var2
            type: String
            description: ""
            value: dasdad
          - name: EXTRA_TAGS
            type: String
            description: ""
            value: ""
        when:
          pipelineStatus: Success
    - stage:
        name: testtemplatestage
        identifier: testtemplatestage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: testtemplatestep
                  identifier: testtemplatestep
                  template:
                    templateRef: testtemp
                    versionLabel: "1"
                    templateInputs:
                      type: ShellScript
                      spec:
                        environmentVariables:
                          - name: var1
                            type: String
                            value: <+input>
                          - name: var2
                            type: String
                            value: <+input>
        tags: {}
  variables:
    - name: testvar
      type: String
      default: ""
      description: ""
      value: <+pipeline.variables.dummy>
    - name: envVar
      type: String
      description: ""
      value: <+input>.allowedValues(abcd,efgh,dasdad,dadad,eqweqe,thdh)
    - name: dummy
      type: String
      description: ""
      value: Host
    - name: somevar
      type: String
      description: ""
      value: abcd_efgh
