pipeline:
  name: temp
  identifier: temp
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: teststage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dummy
                  identifier: dummy
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "printing secret"
                          echo "text secret is: " <+pipeline.variables.testvar>
                          echo "NX_REVEL_GRAPHQL_URL=https://<+pipeline.variables.var1>.dev.revel.vivun.com/api/graphql"
                          echo "NX_REVEL_GRAPHQL_URL=https://"<+pipeline.variables.var1>".dev.revel.vivun.com/api/graphql"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: var1
            type: String
            description: ""
            value: dssadasd
          - name: var2
            type: String
            description: ""
            value: dasdad
          - name: EXTRA_TAGS
            type: String
            description: ""
            value: ""
    - stage:
        name: testtemplatestage
        identifier: testtemplatestage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: testtemplatestep
                  identifier: testtemplatestep
                  template:
                    templateRef: testtemp
                    versionLabel: "1"
                    templateInputs:
                      type: ShellScript
                      spec:
                        environmentVariables:
                          - name: var1
                            type: String
                            value: <+input>
                          - name: var2
                            type: String
                            value: <+input>
        tags: {}
  variables:
    - name: testvar
      type: String
      default: ""
      description: ""
      value: <+secrets.getValue("testsecret")>
