pipeline:
  name: testHelm
  identifier: testHelm
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: helmTestNative
        identifier: helmTestNative
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: helmNativeSvc
          environment:
            environmentRef: gcpinfra
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testinfra
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: K8sDelete
                  name: Delete
                  identifier: Delete
                  spec:
                    deleteResources:
                      type: ManifestPath
                      spec:
                        manifestPaths:
                          - helm-chart-test
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: secretvar
      type: String
      description: ""
      value: <+secrets.getValue("testsecret")>
