pipeline:
  name: testpipeline
  identifier: testpipeline
  template:
    templateRef: testpipelinetemplate
    versionLabel: "1"
    templateInputs:
      stages:
        - stage:
            identifier: deploymentstage
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          type: DockerRegistry
                          spec:
                            tag: <+input>.allowedValues(abcd)
  tags: {}
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
