pipeline:
  name: testpipelinescript
  identifier: testpipelinescript
  projectIdentifier: ajhacseng
  orgIdentifier: CSE
  tags: {}
  stages:
    - stage:
        name: adsd
        identifier: adsd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          abcd=<+secrets.getValue("account.bitbucket_tokenusheer")>

                          cat abc.txt
                    environmentVariables: []
                    outputVariables:
                      - name: abcd
                        type: String
                        value: abcd
                  timeout: 10m
        tags: {}
